#!/usr/bin/env python3
"""
Create YAML Configuration Files for Phase 313

Creates the YAML config files that Phase 313 expects:
- config/system3_global_config.yml
- config/system3_broker_config.yml  
- config/system3_risk_config.yml
"""

import yaml
from pathlib import Path

def create_yaml_config_files():
    """Create all required YAML configuration files"""
    
    config_dir = Path("config")
    config_dir.mkdir(exist_ok=True, parents=True)
    
    print("=" * 70)
    print("PHASE 313 YAML CONFIGURATION GENERATOR")
    print("=" * 70)
    print()
    
    # Global configuration
    global_config = {
        "system": {
            "name": "System3",
            "version": "1.0",
            "environment": "production",
            "description": "Advanced algorithmic trading system"
        },
        "trading": {
            "LIVE_TRADING_ENABLED": False,
            "USE_LIVE_EXECUTION_ENGINE": False,
            "auto_execute_trades": False,
            "paper_trading_enabled": True,
            "description": "Trading execution settings (DRY-RUN)"
        },
        "logging": {
            "level": "INFO",
            "format": "json",
            "output_dir": "logs/",
            "max_file_size_mb": 100,
            "backup_count": 5
        },
        "data": {
            "csv_output_dir": "storage/data/",
            "json_output_dir": "storage/system_health/",
            "logs_output_dir": "logs/"
        }
    }
    
    # Broker configuration
    broker_config = {
        "broker": {
            "name": "Angel One",
            "api_version": "v1",
            "api_timeout_seconds": 30,
            "retry_attempts": 3,
            "retry_delay_seconds": 2
        },
        "authentication": {
            "use_oauth": True,
            "token_refresh_interval_seconds": 3600,
            "secure_storage": True
        },
        "endpoints": {
            "market_data": "https://api.angelbroking.com/v1/market",
            "orders": "https://api.angelbroking.com/v1/orders",
            "positions": "https://api.angelbroking.com/v1/positions",
            "holdings": "https://api.angelbroking.com/v1/holdings"
        },
        "rate_limits": {
            "requests_per_second": 10,
            "orders_per_minute": 30
        }
    }
    
    # Risk configuration
    risk_config = {
        "risk": {
            "max_daily_loss_percent": 2.0,
            "max_position_size_percent": 10.0,
            "max_leverage": 1.0,
            "max_drawdown_percent": 5.0
        },
        "limits": {
            "max_trades_per_day": 100,
            "max_concurrent_positions": 20,
            "min_holding_period_minutes": 5,
            "max_holding_period_hours": 8
        },
        "alerts": {
            "enable_drawdown_alerts": True,
            "enable_margin_alerts": True,
            "enable_position_alerts": True,
            "enable_loss_alerts": True,
            "alert_threshold_percent": 1.0
        },
        "stops": {
            "use_hard_stops": True,
            "stop_loss_percent": 2.0,
            "take_profit_percent": 3.0
        }
    }
    
    configs = {
        "system3_global_config.yml": {
            "config": global_config,
            "description": "Global system configuration"
        },
        "system3_broker_config.yml": {
            "config": broker_config,
            "description": "Broker API configuration"
        },
        "system3_risk_config.yml": {
            "config": risk_config,
            "description": "Risk management configuration"
        }
    }
    
    created_files = []
    
    for filename, details in configs.items():
        filepath = config_dir / filename
        config = details["config"]
        description = details["description"]
        
        print(f"Creating: {filename}")
        print(f"  Description: {description}")
        
        try:
            with open(filepath, 'w') as f:
                # Write custom header
                f.write(f"# {description}\n")
                f.write(f"# Auto-generated by create_yaml_configs.py\n")
                f.write(f"# System3 Configuration\n")
                f.write(f"\n")
                
                # Write YAML content
                yaml.dump(config, f, 
                         default_flow_style=False, 
                         sort_keys=False,
                         allow_unicode=True)
            
            print(f"  ✅ Created: {filepath}")
            created_files.append(filepath)
        
        except Exception as e:
            print(f"  ❌ Error: {e}")
        
        print()
    
    print("=" * 70)
    print(f"SUMMARY: Created {len(created_files)} configuration files")
    print("=" * 70)
    print()
    
    if created_files:
        print("✅ Files created:")
        for f in created_files:
            print(f"  - {f}")
        print()
        print("✅ Phase 313 should now return OK status instead of ERROR")
        print()
        print("Next steps:")
        print("  1. Review the YAML files in config/")
        print("  2. Customize settings as needed")
        print("  3. Re-run tests: python test_phases_311_330.py")
    
    return len(created_files)

if __name__ == "__main__":
    create_yaml_config_files()
