"""
System3 LSTM Evaluation & Promotion Utilities

Provides robust helpers for Phase 250-255 pipeline:
- Read latest Phase 249 Extended evaluation JSON
- Safe fallbacks and error handling
- Integrated System3 logging

Date: 2025-12-06
"""

import sys
import json
import logging
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional, List
import glob

PROJECT_ROOT = Path(__file__).parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# Directories
LOGS_DIR = PROJECT_ROOT / "logs"


def read_latest_evaluation_metrics(
    eval_dir: str = "logs",
    pattern: str = "phase249_model_evaluation_*.json",
    min_required_keys: Optional[List[str]] = None,
) -> Optional[Dict[str, Any]]:
    """
    Read the latest Phase 249 Extended evaluation JSON.

    This function finds the most recent evaluation report generated by
    evaluate_phase249_models.py and returns its contents safely.

    Args:
        eval_dir: Directory containing evaluation JSON files (relative to project root or absolute)
        pattern: Glob pattern to match evaluation files
        min_required_keys: Required keys in the JSON (default: ['models', 'evaluation_timestamp'])

    Returns:
        Dict with evaluation metrics, keyed by model name, or None if no valid file found.

        Structure:
        {
            'evaluation_timestamp': '2025-12-06T14:30:45.123456',
            'total_models': 5,
            'models': {
                'NIFTY': {
                    'status': 'SUCCESS',
                    'accuracy': 0.462,
                    'precision': 0.0,
                    'recall': 0.0,
                    'f1_score': 0.0,
                    'test_samples': 13,
                    'training_accuracy': 0.875,
                    'online_learning_count': 0,
                    'evaluation_timestamp': '2025-12-06T00:18:46'
                },
                ...
            },
            'summary': {
                'evaluated_models': 3,
                'avg_accuracy': 0.573,
                'min_accuracy': 0.462,
                'max_accuracy': 0.655,
                'std_accuracy': 0.089
            }
        }

    Raises:
        None - always returns either a dict or None, never raises
    """

    # Set default required keys
    if min_required_keys is None:
        min_required_keys = ["models", "evaluation_timestamp"]

    # Resolve directory path
    if not Path(eval_dir).is_absolute():
        eval_path = PROJECT_ROOT / eval_dir
    else:
        eval_path = Path(eval_dir)

    # Ensure directory exists
    if not eval_path.exists():
        logger.warning(f"[LSTM_UTILS] Evaluation directory not found: {eval_path}")
        return None

    try:
        # Prefer explicit pointer file (written by evaluate_phase249_models.py)
        pointer_path = eval_path / "phase249_latest_eval_path.txt"
        if pointer_path.exists():
            try:
                with open(pointer_path, "r") as f:
                    latest_file = f.read().strip()
                if latest_file and Path(latest_file).exists():
                    logger.info(f"[LSTM_UTILS] Reading latest evaluation (pointer): {latest_file}")
                else:
                    latest_file = None
            except Exception as e:
                logger.warning(f"[LSTM_UTILS] Could not read pointer file: {e}")
                latest_file = None
        else:
            latest_file = None

        # Fallback: glob by pattern, then pick latest by mtime
        if not latest_file:
            search_pattern = str(eval_path / pattern)
            matching_files = glob.glob(search_pattern)
            if not matching_files:
                logger.warning(f"[LSTM_UTILS] No evaluation files found matching pattern: {search_pattern}")
                return None
            latest_file = max(matching_files, key=lambda p: Path(p).stat().st_mtime)
            logger.info(f"[LSTM_UTILS] Reading latest evaluation (glob): {latest_file}")

        # Load JSON
        with open(latest_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Validate required keys
        missing_keys = [key for key in min_required_keys if key not in data]
        if missing_keys:
            logger.warning(f"[LSTM_UTILS] Evaluation JSON missing required keys: {missing_keys}")
            return None

        # Validate models key is a dict
        if not isinstance(data.get("models"), dict):
            logger.warning(f"[LSTM_UTILS] 'models' key is not a dictionary")
            return None

        logger.info(f"[LSTM_UTILS] Successfully loaded evaluation metrics for {len(data['models'])} models")
        return data

    except json.JSONDecodeError as e:
        logger.warning(f"[LSTM_UTILS] Failed to parse evaluation JSON: {e}")
        return None

    except Exception as e:
        logger.warning(f"[LSTM_UTILS] Unexpected error reading evaluation metrics: {e}")
        return None


def extract_model_metrics(evaluation_data: Dict[str, Any], underlying: str) -> Optional[Dict[str, Any]]:
    """
    Extract metrics for a specific underlying from evaluation data.

    Args:
        evaluation_data: Full evaluation dict from read_latest_evaluation_metrics()
        underlying: Underlying symbol (e.g., 'NIFTY')

    Returns:
        Dict with model metrics or None if not found/invalid
    """
    if evaluation_data is None:
        return None

    models = evaluation_data.get("models", {})

    if underlying not in models:
        logger.warning(f"[LSTM_UTILS] No evaluation data for {underlying}")
        return None

    model_data = models[underlying]

    # Check if evaluation was successful
    if model_data.get("status") != "SUCCESS":
        logger.warning(f"[LSTM_UTILS] {underlying} evaluation failed: {model_data.get('reason', 'unknown')}")
        return None

    return model_data


def compare_to_baseline(
    current_accuracy: float, baseline_accuracy: float = 0.55, degradation_threshold: float = 0.10
) -> Dict[str, Any]:
    """
    Compare current accuracy to baseline.

    Args:
        current_accuracy: Current model accuracy
        baseline_accuracy: Baseline threshold (default 55%)
        degradation_threshold: Maximum allowed accuracy loss (default 10%)

    Returns:
        Dict with comparison results:
        {
            'passes_baseline': bool,
            'passes_stability': bool,
            'current_accuracy': float,
            'baseline_accuracy': float,
            'degradation_percent': float,
            'status': 'OK' | 'DRIFT_LOW' | 'DRIFT_DEGRADED'
        }
    """

    passes_baseline = current_accuracy >= baseline_accuracy
    degradation_loss = baseline_accuracy - current_accuracy
    passes_stability = degradation_loss <= degradation_threshold

    if passes_baseline and passes_stability:
        status = "OK"
    elif not passes_baseline:
        status = "DRIFT_LOW"
    else:
        status = "DRIFT_DEGRADED"

    return {
        "passes_baseline": passes_baseline,
        "passes_stability": passes_stability,
        "current_accuracy": current_accuracy,
        "baseline_accuracy": baseline_accuracy,
        "degradation_percent": degradation_loss,
        "status": status,
    }


def write_promotion_decision(
    decision: Dict[str, Any], decision_dir: str = "logs", filename: str = "phase251_promotion_decision.json"
) -> Optional[Path]:
    """
    Write Phase 251 promotion decision to JSON.

    Args:
        decision: Decision dict from Phase 251
        decision_dir: Directory to write decision file
        filename: Filename for decision JSON

    Returns:
        Path to written file, or None if write failed
    """

    # Resolve directory
    if not Path(decision_dir).is_absolute():
        decision_path = PROJECT_ROOT / decision_dir
    else:
        decision_path = Path(decision_dir)

    # Ensure directory exists
    decision_path.mkdir(parents=True, exist_ok=True)

    try:
        output_file = decision_path / filename

        with open(output_file, "w", encoding="utf-8") as f:
            json.dump(decision, f, indent=2)

        logger.info(f"[LSTM_UTILS] Promotion decision written: {output_file}")
        return output_file

    except Exception as e:
        logger.error(f"[LSTM_UTILS] Failed to write promotion decision: {e}")
        return None


def read_promotion_decision(
    decision_dir: str = "logs", filename: str = "phase251_promotion_decision.json"
) -> Optional[Dict[str, Any]]:
    """
    Read the latest Phase 251 promotion decision JSON.

    Args:
        decision_dir: Directory containing decision file
        filename: Filename for decision JSON

    Returns:
        Decision dict or None if not found
    """

    # Resolve directory
    if not Path(decision_dir).is_absolute():
        decision_path = PROJECT_ROOT / decision_dir
    else:
        decision_path = Path(decision_dir)

    decision_file = decision_path / filename

    if not decision_file.exists():
        logger.warning(f"[LSTM_UTILS] Promotion decision file not found: {decision_file}")
        return None

    try:
        with open(decision_file, "r", encoding="utf-8") as f:
            decision = json.load(f)

        logger.info(f"[LSTM_UTILS] Loaded promotion decision from {decision_file}")
        return decision

    except Exception as e:
        logger.warning(f"[LSTM_UTILS] Failed to read promotion decision: {e}")
        return None
