#!/usr/bin/env python3
"""
Production-grade phase registry rebuild.
- Scans core/engine for all system3_phase*.py files
- Detects run_phaseXXX callables when present
- Writes normalized registry to storage/meta/system3_phase_registry.json

This makes Phase 312 report OK by keeping registry and implementations in sync.
"""

from __future__ import annotations

import importlib.util
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

PROJECT_ROOT = Path(__file__).parent
ENGINE_DIR = PROJECT_ROOT / "core" / "engine"
LEGACY_ENGINE_DIR = PROJECT_ROOT / "engine" / "phases"
REGISTRY_PATH = PROJECT_ROOT / "storage" / "meta" / "system3_phase_registry.json"


def discover_phase_files() -> List[Path]:
    # Collect phase files from both modern and legacy directories.
    phase_files = list(ENGINE_DIR.glob("system3_phase*.py"))
    if LEGACY_ENGINE_DIR.exists():
        phase_files.extend(LEGACY_ENGINE_DIR.glob("system3_phase*.py"))
    return sorted(phase_files)


def extract_phase_number(path: Path) -> int | None:
    match = re.search(r"phase(\d+)", path.stem)
    return int(match.group(1)) if match else None


def has_run_callable(path: Path, phase_num: int) -> bool:
    func_name = f"run_phase{phase_num}"
    try:
        spec = importlib.util.spec_from_file_location(path.stem, path)
        if spec is None or spec.loader is None:
            return False
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)  # type: ignore[arg-type]
        attr = getattr(module, func_name, None)
        return callable(attr)
    except Exception:
        return False


def build_registry() -> List[Dict]:
    entries: List[Dict] = []
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    for phase_file in discover_phase_files():
        phase_num = extract_phase_number(phase_file)
        if phase_num is None:
            continue

        callable_present = has_run_callable(phase_file, phase_num)
        entry = {
            "phase": phase_num,
            "name": phase_file.stem,
            "module_name": phase_file.stem,
            "file_path": str(phase_file.relative_to(PROJECT_ROOT)),
            "implemented": True,
            "callable_verified": callable_present,
            "method_signature": f"run_phase{phase_num}(**kwargs) -> Dict[str, Any]",
            "added_date": now,
            "notes": "auto-generated by rebuild_phase_registry_complete.py",
        }
        entries.append(entry)

    entries.sort(key=lambda x: x["phase"])
    return entries


def write_registry(entries: List[Dict]) -> None:
    REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
    REGISTRY_PATH.write_text(json.dumps(entries, indent=2), encoding="utf-8")


def main() -> None:
    print("Scanning core/engine for phase implementations...")
    entries = build_registry()
    write_registry(entries)
    print(f"✅ Registry rebuilt: {len(entries)} entries written → {REGISTRY_PATH}")


if __name__ == "__main__":
    main()
