substitutions:
  _REGION: asia-south1
  _REPOSITORY: system3-containers
  _IMAGE: genesis-system3

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=dashboard/backend/Dockerfile
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
